"""Add game_mode column to players table

Revision ID: 23d56873f1dd
Revises: f065a88c4a27
Create Date: 2025-11-02 23:07:50.095138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23d56873f1dd"
down_revision: Union[str, Sequence[str], None] = "f065a88c4a27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column(
        "players",
        sa.Column(
            "game_mode",
            sa.Enum("REGULAR", "IRONMAN", "HARDCORE_IRONMAN", name="gamemode"),
            nullable=True,
        ),
    )

    # Set default value for existing players
    op.execute(
        "UPDATE players SET game_mode = 'REGULAR' WHERE game_mode IS NULL"
    )

    # Make the column non-nullable
    op.alter_column("players", "game_mode", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "game_mode")
    # ### end Alembic commands ###
