from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base

if TYPE_CHECKING:
    from .player import Player


class PlayerSummary(Base):
    """
    Model representing an AI-generated summary of player progress.

    This model stores summaries generated by OpenAI that analyze player progress
    over the last day and week, providing insights into their gameplay patterns.
    """

    __tablename__ = "player_summaries"

    # Primary key
    id: Mapped[int] = mapped_column(primary_key=True)

    # Foreign key to player
    player_id: Mapped[int] = mapped_column(
        ForeignKey("players.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Reference to the player this summary belongs to",
    )

    # Summary period
    period_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        doc="Start of the period covered by this summary",
    )

    period_end: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        doc="End of the period covered by this summary",
    )

    # Summary content
    summary_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="AI-generated summary text",
    )

    # Metadata
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
        doc="When this summary was generated",
    )

    # Optional metadata about the generation
    model_used: Mapped[str] = mapped_column(
        String(100),
        nullable=True,
        doc="OpenAI model used for generation (e.g., 'gpt-4', 'gpt-3.5-turbo')",
    )

    # Relationships
    player: Mapped[Player] = relationship(
        "Player",
        back_populates="summaries",
        doc="The player this summary belongs to",
    )

    def __repr__(self) -> str:
        """String representation of the summary."""
        return (
            f"<PlayerSummary(id={self.id}, player_id={self.player_id}, "
            f"generated_at={self.generated_at})>"
        )
